version: '3.1'
services:
  webapp:
    image: registry.digitalocean.com/kubishi-registry/kubishi:v0.0.2
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=3000
    # command: tail -f /dev/null