
const PartOfSpeech = [
    'NOUN',
    'VERB',
    'IDIOM',
    'ADVERB',
    'PRONOUN',
    'ADJECTIVE',
    'NOUN_SUFFIX',
    'NOUN_PREFIX',
    'VERB_SUFFIX',
    'VERB_PREFIX',
    'PREPOSITION',
    'POSTPOSITION',
    'CONJUNCTION',
    'INTERJECTION',
    'INSTRUMENTAL_PREFIX',
    'ADVERBIAL_SUFFIX',
    'ADVERBIAL_PREFIX',
    'ADJECTIVIAL_SUFFIX',
    'ADJECTIVIAL_PREFIX',
    'PARTICLE',
    'POSSESSIVE PRONOUN',
    'UNKNOWN',
];

export default PartOfSpeech;